services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
          - "5173:5173"
        volumes:
            - ./frontend/src:/app/src
            - frontend_nodes_modules:/app/node_modules

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        env_file:
            - ./backend/.env
        ports:
          - "8000:8000"
        volumes:
            - ./backend/src:/app/src/
        depends_on:
            - postgres
            - rabbitmq

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        env_file:
            - ./rabbitmq/.env
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq

    postgres:
        container_name: postgres
        image: postgres:latest
        env_file:
            - ./database/.env
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

networks:
    default:
        driver: bridge

volumes:
    pgdata:
    backend_app:
    rabbitmq_data:
    frontend_nodes_modules:
