services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment:
            VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        ports:
            - "5173:5173"
        volumes:
            - ./frontend/src:/app/src
            - frontend_nodes_modules:/app/node_modules

    backend:
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile.dev
        environment:
            RABBIT_PORT: ${RABBITMQ_PORT}
            RABBIT_HOST: ${RABBITMQ_HOST}
            RABBIT_USER: ${RABBITMQ_USER}
            RABBIT_PASSWORD: ${RABBITMQ_PASS}
            RABBIT_VIRTUAL_HOST: ${RABBITMQ_VHOST}
        ports:
            - "8000:8000"
        volumes:
            - ./backend/src:/app/src/
        depends_on:
            - postgres
            - rabbitmq

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/data/postgres

networks:
    default:
        driver: bridge

volumes:
    pgdata:
    backend_app:
    rabbitmq_data:
    frontend_nodes_modules:
