services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment:
            VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        ports:
            - "5173:5173"
        volumes:
            - ./frontend/src:/app/src
            - frontend_nodes_modules:/app/node_modules

    backend:
        build:
            context: backend
            dockerfile: Dockerfile.dev
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            RABBIT_PORT: ${RABBITMQ_PORT}
            RABBIT_HOST: ${RABBITMQ_HOST}
            RABBIT_USER: ${RABBITMQ_USER}
            RABBIT_PASSWORD: ${RABBITMQ_PASS}
            RABBIT_VIRTUAL_HOST: ${RABBITMQ_VHOST}
            DOCSERVER_PATH: /app/docservers
        ports:
            - "8100:8000"
        volumes:
            - ./custom:/app/custom/
            - ./backend/src:/app/src/
            - ./backend/instance:/app/instance/
            - ${DOCSERVERS_PATH}:/app/docservers/
        depends_on:
            - postgres
            - rabbitmq

    worker_verifier:
        build:
            context: backend
            dockerfile: Dockerfile.dev
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            RABBIT_PORT: ${RABBITMQ_PORT}
            RABBIT_HOST: ${RABBITMQ_HOST}
            RABBIT_USER: ${RABBITMQ_USER}
            RABBIT_PASSWORD: ${RABBITMQ_PASS}
            RABBIT_VIRTUAL_HOST: ${RABBITMQ_VHOST}
            DOCSERVER_PATH: /app/docservers
        volumes:
            - ./custom:/app/custom/
            - ./backend/src:/app/src/
            - ./backend/instance/:/app/instance/
            - ${DOCSERVERS_PATH}:/app/docservers/
        entrypoint: ./run_verifier_worker.sh
        depends_on:
            - postgres
            - rabbitmq

    rabbitmq:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    postgres:
        build:
            context: postgres
            dockerfile: Dockerfile.dev
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/data/postgres

networks:
    default:
        driver: bridge

volumes:
    pgdata:
    backend_app:
    rabbitmq_data:
    frontend_nodes_modules:
