FROM postgres:17.6

COPY sql/structure.sql /docker-entrypoint-initdb.d/01_structure.sql
COPY sql/data_fr.sql  /docker-entrypoint-initdb.d/02_data_fr.sql
COPY sql/global  /docker-entrypoint-initdb.d/03_global.sql

EXPOSE 5432